var console = require('gulp-messenger');

var items = ["Accession Number", "Client Information", "   Additional Recipients", "   Contact Id", "   Fax Number", "   Institution Address", "   Institution Name", "   Organization Id", "   Ph Number", "   Physician", "Patient Information", "   Age", "   DOB", "   Ethnicity", "   Family #", "   Gender", "   Indication", "   MRN #", "   Patient Name", "   Specimen", "      Collected Date", "      Name", "      Number", "      Received Date", "   Test Authorization Date", "Product Code", "Ready to Report (Yes/No)", "Report Assigned To GC/MD", "Report Assigned To Group", "Report Generated By", "Report Generation Date", "Report Options", "Is Negative? (Yes/No)", "Polys/VLBs Included? (Yes/No)", "Report Sub Type", "Report Summary", "Report Title", "Report Type", "Reported Alterations", "Reported Polys/VLBs", "Reporting Status", "Signed By", "Signed Date", "Signed? (Yes/No)", "Supplementary", "Test Name"];

console.dump(items);
